name: Backend CI

on: 
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        cd backend
        pipenv install

    - name: Run Linter
      run: |
        cd backend
        pipenv run lint

  test:
    name: Test Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        cd backend
        pipenv install

    - name: Run Tests
      run: |
        cd backend
        pipenv run test

  build:
    name: Build Docker Image for Backend
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9


    - name: Build the Docker image
      run: |
        cd backend
        docker build --tag mp-backend:latest .

    - name: Run the Docker image
      run: |
        docker run -p 5000:5000 --name mp-backend -d mp-backend
        sleep 15 # giving some time for the server to start

    - name: Check the running application
      run: |
        curl http://localhost:5000/movies