name: Frontend Continuous Integration

on: 
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Install Dependencies
      run: |
        cd starter/frontend
        npm ci

    - name: Lint
      run: |
        cd starter/frontend
        npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Install Dependencies
      run: |
        cd starter/frontend
        npm ci

    - name: Run Tests
      run: |
        cd starter/frontend
        npm test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Install Dependencies
      run: |
        cd starter/frontend
        npm ci

    - name: Build
      run: |
        cd starter/frontend
        npm run build
